{"name": "test_div[div-zero]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 100\n  +None\n  -100", "trace": "self = <test_pytest_HT.test_calc_new.TestCalc object at 0x000001BF0F933DD8>\nget_calc = <test_pytest_HT.calculator.Calculator object at 0x000001BF0F87F1D0>, get_div_datas = [100, 0, 100]\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       assert None == 100\nE         +None\nE         -100\n\ntest_calc_new.py:38: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[100, 0, 100]"}], "start": 1610373753665, "stop": 1610373753665, "uuid": "03504e4c-0fae-4ec6-9b11-cba803a39378", "historyId": "8b12cbf10524ce7fbb6f66bc105b0bc8", "testCaseId": "609ad21c188e7e060f5fa127da920487", "fullName": "test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "3300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}