{"name": "test_add[add-other]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'qqqq' == 'qq'\n  - qq\n  + qqqq", "trace": "self = <test_pytest_HT.test_calc_new.TestCalc object at 0x000001BF0F87FAC8>\nget_calc = <test_pytest_HT.calculator.Calculator object at 0x000001BF0F87F1D0>, get_add_datas = ['qq', 'qq', 'qq']\n\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_add_datas):\n        # pass\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_add_datas[0], get_add_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_add_datas[2]\nE       AssertionError: assert 'qqqq' == 'qq'\nE         - qq\nE         + qqqq\n\ntest_calc_new.py:26: AssertionError"}, "parameters": [{"name": "get_add_datas", "value": "['qq', 'qq', 'qq']"}], "start": 1610373753565, "stop": 1610373753565, "uuid": "70e89302-2881-48d6-bbed-e00ea3588c82", "historyId": "6f3c0550fc35ef8a18993c40b0d9b632", "testCaseId": "07d7074b11baf99ef0f511221e36f260", "fullName": "test_calc_new.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "3300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}